### ISSUE TITLE
Research: deploy node to a service that will host it on a specific domain

### ISSUE THREAD

**Issue by XiXiaPdx** [AntonEmery/chord-app#26]
Which hosting service?  How is it done? Docker?  

Acceptance criteria: 

Document the research and steps to make this happen.

**Comment by AntonEmery** [comment]
This seems like a good place to start

https://stackabuse.com/deploying-a-node-js-app-to-a-digitalocean-droplet-with-docker/

**Comment by XiXiaPdx** [comment]
> This seems like a good place to start
> 
> https://stackabuse.com/deploying-a-node-js-app-to-a-digitalocean-droplet-with-docker/
> 
> Also this, which uses github actions
> https://blog.bitsrc.io/https-medium-com-adhasmana-how-to-do-ci-and-cd-of-node-js-application-using-github-actions-860007bebae6
> 
> Will have to do some more reading I think

Looks good. 

The github action article looks like where we should start and get the docker image published to DockerHub.
The second article is useful in explaining how to wire up Dockerhub and Digital ocean
