### ISSUE TITLE
Research: How to get variables.env file out of the docker image

### ISSUE THREAD

**Issue by XiXiaPdx** [AntonEmery/chord-app#31]
It is recommended not to pass secrets or config files into your docker image.  

Research how to avoid this

**Comment by AntonEmery** [comment]
This seems to be a way
https://medium.com/@felipedutratine/pass-environment-variables-from-docker-to-my-nodejs-or-golang-app-a1f2ddec31f5

**Comment by AntonEmery** [comment]
Initial commit on this issue, adding a reference to the variables.env file when starting docker.  https://github.com/AntonEmery/chord-app/commit/5438755a75fa6e710c15b880405a750586456782

If you use #issue-number in your commit msg it will place a reference to that commit in the issue, as you can see above. Kind of nice.

I can't seem to start up the Docker container in this branch, curious if you can.
```
Step 4/8 : RUN npm install
 ---> Running in d18d8716e406
npm ERR! write after end
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-13T20_32_16_049Z-debug.log
```

**Comment by XiXiaPdx** [comment]
Oh, I see how that works with the message. Nice!

I'll take a look

**Comment by AntonEmery** [comment]
There was a typo in the Dockerfile `package*.json` that I think was causing the error.  

It looks like `nodemon` is not restarting the server now when running with Docker

**Comment by AntonEmery** [comment]
@XiXiaPdx I removed the import of the .env file from Node, they are now being passed in via Docker and seem to be working. (I can login to the app).  I am now trying to figure out how to SSH into the Docker container to confirm that the file is not being copied over.  Should that be a separate issue?
