### ISSUE TITLE
Upload docker container to dockerhub

### ISSUE THREAD

**Issue by AntonEmery** [AntonEmery/chord-app#36]
Figure out how to upload docker container to Dockerhub.  First manually, then automate through Github actions.

**Comment by AntonEmery** [comment]
I've got an account setup on Dockerhub

https://docs.github.com/en/actions/guides/publishing-docker-images

**Comment by AntonEmery** [comment]
@XiXiaPdx I've got a build working on Dockerhub when a push is made to `master` here. I didn't need to involve GH Actions, so maybe its not needed?  If you setup an account on Dockerhub I can add you to the repo

**Comment by AntonEmery** [comment]
Currently I am trying to figure out how to build my image on dockerhub in prod mode, instead of using `devNoClient`

**Comment by XiXiaPdx** [comment]
Cool!  my username is xixiapdx on docker hub

**Comment by AntonEmery** [comment]
I've added you on Dockerhub. If you click on Builds down in the bottom under Recent Builds you can click on them and view the build process. Configure Automated Builds will show you the various build options.

**Comment by XiXiaPdx** [comment]
I'm not seeing anything in my docker hub. Do you have a link to your image?

**Comment by AntonEmery** [comment]
Hmm, all it says is collaborators will be given push and pull access to the repo.  So I am not sure if you will see anything in Dockerhub?  Here is the dockerhub repo.  https://hub.docker.com/repository/docker/antonemery/chord-app

**Comment by AntonEmery** [comment]
After a bunch of searching around I might be getting somewhere.  This article was useful.
https://medium.com/@habibridho/docker-as-deployment-tools-5a6de294a5ff

I'm still trying to get an idea of the big picture.  I think it might be?
1. Push my image to Dockerhub from Github, but don't build it
2. On the server that is going to host the back end `docker pull antonemery/chord-app`. Maybe this is triggered with a web hook?
3. Once the docker image is on the server run start it in `prod` mode

**Comment by AntonEmery** [comment]
I think maybe just following something like this is the best idea, its exactly what we want to do.  

https://medium.com/wolox/hello-and-welcome-to-our-new-post-fa53900fd173

**Comment by XiXiaPdx** [comment]
> After a bunch of searching around I might be getting somewhere. This article was useful.
> https://medium.com/@habibridho/docker-as-deployment-tools-5a6de294a5ff
> 
> I'm still trying to get an idea of the big picture. I think it might be?
> 
> 1. Push my image to Dockerhub from Github, but don't build it
> 2. On the server that is going to host the back end `docker pull antonemery/chord-app`. Maybe this is triggered with a web hook?
> 3. Once the docker image is on the server run start it in `prod` mode

Yeah, you got it!

I think I found a great guide and it clears up whatbwe need to do with Digital Ocean.

https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-github-actions/

Here is another, less perfect but still very helpful.

https://stackabuse.com/deploying-a-node-js-app-to-a-digitalocean-droplet-with-docker/

**Comment by AntonEmery** [comment]
Those two articles looked good, finally got some mental bandwidth to read over them. So it looks like we don't need dockerhub?  Seems like we can just github and deploy to DO.  If so, I'll delete my dockerhub project.

I need to read them again, but maybe the next best step would be to implement this together over a bigger chunk of time?
