### ISSUE TITLE
Allow back end to accept requests from client

### ISSUE THREAD

**Issue by AntonEmery** [AntonEmery/chord-app#56]
@XiXiaPdx I've got the react client deployed to Netlify.
https://serene-easley-3b3411.netlify.app/

They make it quite easy to point to folder or sub folder in your repo, build it, and deploy it.
https://docs.netlify.com/configure-builds/get-started/#basic-build-settings

So I have it pointed to `src/client` and it builds directly from there.
I added an env variable in Netlify that points to the back end IP address

Now I need to update the Node backend to allow requests from the front end URL

**Comment by XiXiaPdx** [comment]
Awesome!  If you already have a map of what needs to be done in the backend, and the challenges, can you outline them here in stepwise fashion?

**Comment by XiXiaPdx** [comment]
@AntonEmery  I believe this can be closed

**Comment by AntonEmery** [comment]
Front end is now deployed to Netlify.  Closing
