### ISSUE TITLE
Research: Add Nginx server via another docker container

### ISSUE THREAD

**Issue by XiXiaPdx** [AntonEmery/chord-app#58]
Do we need a nginx server to enable ssl for docker container of nodejs app???

This is a comprehensive article. Implies no need for nginx but also has directions for it
https://techsparx.com/nodejs/docker/express-https.html

This is a DO community tutorial , with nginx
https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose

This is a simpler guide to just get nginx setup
https://dev.to/destrodevshow/docker-201-use-nginx-as-a-proxy-for-nodejs-server-in-2020-practical-guide-57ji

**Comment by AntonEmery** [comment]
I got SSL running on the server using this tutorial.

https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

I am now getting a CORS error on the front end when I try to login, which is as it should be.  I need to update the server code to allow the front end url as an origin. 

Give it a try.
https://serene-easley-3b3411.netlify.app/

I believe this closes the issue.  Server is running on SSL, client makes the request to login and gets a CORS error.
