### ISSUE TITLE
Forwarded port 8080 to chord-app domain name

### ISSUE THREAD

**Issue by AntonEmery** [AntonEmery/chord-app#59]
@XiXiaPdx 

I installed Nginx on the Droplet and set it up so port 8080 gets forwarded to `chord-app.com`

[Chord App](http://www.chord-app.com)

How I installed Nginx
https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-20-04

Added the block of code that does the port proxying
https://www.digitalocean.com/community/questions/how-do-i-point-my-custom-domain-to-my-ip-port-41-111-20-36-8080

**Comment by XiXiaPdx** [comment]
Nice! Can this be closed?

**Comment by AntonEmery** [comment]
This has been solved, closing issue
