### ISSUE TITLE
Setup one Unit Test

### ISSUE THREAD

**Issue by XiXiaPdx** [AntonEmery/chord-app#63]
Acceptance criteria:

1) Setup one unit test for express backend
2) Update readme on how to run tests locally

**Comment by AntonEmery** [comment]
I've got a basic install of Jest and a simple test passing, now need to figure out how to run all this from inside the Docker container.  Created a draft PR.

https://github.com/AntonEmery/chord-app/pull/87

**Comment by AntonEmery** [comment]
Trying to figure out how to get this all going inside of Docker.  Do we need a separate container for running tests?  Check out the article here under `Our First Test` where he talks about setting up the Docker Compose file.

https://www.freecodecamp.org/news/end-to-end-api-testing-with-docker/

**Comment by XiXiaPdx** [comment]
So this is my understanding, starting with the 3 general levels of testing: 

1) Unit ( e.g. test that isolates one method in the app, everything is else controlled/mocked like external dependencies of database)
2) Functional (e.g. test that requires multiple units to be in play)
3) Integration aka End to End ( use a real database to test an endpoint)

That article is about to End to End testing and why Docker would be great for that. 

I don't think we are building End to End yet. We are working on unit tests first. 

this article about unit testing routes looks helpful.  It talks about separating the controller from the routes. I'm not familiar with express to see those elements in the app, if they are there. 

https://stackoverflow.com/questions/9517880/how-does-one-unit-test-routes-with-express

**Comment by AntonEmery** [comment]
Yea i think that understanding is correct.  Right now my initial step is to get Jest tests running in Docker.  If Docker were not involved I would just open a new terminal window and run `npm test` which would run the Jest tests.  Ideally it would always be running while i code and perhaps watching certain files for changes.  I am not sure how to accomplish this in Docker.

**Comment by AntonEmery** [comment]
I got an initial working for the home route.
PR https://github.com/AntonEmery/chord-app/pull/88

I intended to look at mocking the database and all that we talked about but I just did not have the bandwidth tonight. 

Closing this, we can open another issue for the next test.
