### ISSUE TITLE
Update React class components

### ISSUE THREAD

**Issue by AntonEmery** [AntonEmery/chord-app#89]
Update all React Class components to function components.  Remove lifecycle methods and replace them with hooks.

@XiXiaPdx This might be a fun one if you want to dig into some React code.  We could go through a few together if you want, or you are also free to dive in if you like.

**Comment by XiXiaPdx** [comment]
Sounds good! Can we break this up into separate issues for each component?  Or, make other issues that are component specific and tie them back to this one?

**Comment by AntonEmery** [comment]
@XiXiaPdx Yea that definitely makes more sense.  Ill close this one and then we can open an issue per component
